version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    main: ./cmd/mcp-adapter
    binary: mcp-adapter
    ldflags:
      - -s -w
      - -X github.com/xenixo/mcp-adapter/internal/cli.Version={{.Version}}
      - -X github.com/xenixo/mcp-adapter/internal/cli.Commit={{.Commit}}
      - -X github.com/xenixo/mcp-adapter/internal/cli.BuildDate={{.Date}}

archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: xenixo
    name: mcp-adapter
